export type CanvasColorTheme = "light" | "dark" | "warm";
export type CanvasBackgroundMode = "dots" | "lines" | "blank";

export const canvasThemes = {
    light: {
        name: "light",
        canvas: {
            background: "#f7f9f5",
            dot: "rgba(42,51,48,.20)",
            line: "rgba(42,51,48,.10)",
            selectionStroke: "#2a3330",
            selectionFill: "rgba(42,51,48,.05)",
        },
        node: {
            label: "#5f6d66",
            fill: "#edf1ed",
            panel: "#ffffff",
            panelHover: "#f4f7f3",
            stroke: "#dde2dc",
            activeStroke: "#2a3330",
            placeholder: "#9aa49e",
            text: "#2a3330",
            muted: "#67726b",
            faint: "#aab3ad",
        },
        toolbar: {
            panel: "rgba(255,255,255,.96)",
            border: "#dde2dc",
            item: "#5f6d66",
            itemHover: "#edf1ed",
            activeBg: "#edf1ed",
            activeText: "#2a3330",
        },
        type: {
            image: "#4e7c5d",
            video: "#a0713f",
            text: "#5c7fa3",
            config: "#9a7fa6",
            audio: "#4e7c5d",
            director: "#5c7fa3",
            group: "#aab3ad",
            danger: "#b0564b",
        },
    },
    dark: {
        name: "dark",
        canvas: {
            background: "#161a18",
            dot: "rgba(244,246,242,.22)",
            line: "rgba(244,246,242,.10)",
            selectionStroke: "#eef1ee",
            selectionFill: "rgba(238,241,238,.10)",
        },
        node: {
            label: "#c4ccc7",
            fill: "#232a26",
            panel: "#1d221f",
            panelHover: "#232a26",
            stroke: "#3a423d",
            activeStroke: "#eef1ee",
            placeholder: "#8a948e",
            text: "#eef1ee",
            muted: "#c4ccc7",
            faint: "#8a948e",
        },
        toolbar: {
            panel: "rgba(29,34,31,.96)",
            border: "#3a423d",
            item: "#c4ccc7",
            itemHover: "#232a26",
            activeBg: "#29332e",
            activeText: "#eef1ee",
        },
        type: {
            image: "#7fa88c",
            video: "#c08e4f",
            text: "#7e9dbf",
            config: "#9a8ab5",
            audio: "#7fa88c",
            director: "#7e9dbf",
            group: "#8a948e",
            danger: "#c97a6f",
        },
    },
    // 创作台浅白灰绿（与全局主题同源：#75827C 鼠尾草灰绿）
    warm: {
        name: "warm",
        canvas: {
            background: "#f4f6f2",
            dot: "rgba(117,130,124,.20)",
            line: "rgba(117,130,124,.12)",
            selectionStroke: "#2a3330",
            selectionFill: "rgba(42,51,48,.06)",
        },
        node: {
            label: "#67726b",
            fill: "#e7ece8",
            panel: "#ffffff",
            panelHover: "#f7f9f5",
            stroke: "#dde2dc",
            activeStroke: "#75827c",
            placeholder: "#9aa49e",
            text: "#2a3330",
            muted: "#67726b",
            faint: "#9aa49e",
        },
        toolbar: {
            panel: "rgba(255,255,255,.96)",
            border: "#dde2dc",
            item: "#67726b",
            itemHover: "#e7ece8",
            activeBg: "#e7ece8",
            activeText: "#2a3330",
        },
        type: {
            image: "#4e7c5d",
            video: "#a0713f",
            text: "#5c7fa3",
            config: "#9a7fa6",
            audio: "#4e7c5d",
            director: "#5c7fa3",
            group: "#9aa49e",
            danger: "#b0564b",
        },
    },
} as const;

export type CanvasTheme = (typeof canvasThemes)[CanvasColorTheme];
