export type CanvasColorTheme = "light" | "dark" | "warm";
export type CanvasBackgroundMode = "dots" | "lines" | "blank";

export const canvasThemes = {
    light: {
        name: "light",
        canvas: {
            background: "#f9f7f5",
            dot: "rgba(51, 47, 42,.20)",
            line: "rgba(51, 47, 42,.10)",
            selectionStroke: "#332f2a",
            selectionFill: "rgba(51, 47, 42,.05)",
        },
        node: {
            label: "#6c6660",
            fill: "#f1efed",
            panel: "#ffffff",
            panelHover: "#f7f5f3",
            stroke: "#e2dfdc",
            activeStroke: "#332f2a",
            placeholder: "#a49f9a",
            text: "#332f2a",
            muted: "#726d67",
            faint: "#b3aeaa",
        },
        toolbar: {
            panel: "rgba(255,255,255,.96)",
            border: "#e2dfdc",
            item: "#6c6660",
            itemHover: "#f1efed",
            activeBg: "#f1efed",
            activeText: "#332f2a",
        },
        type: {
            image: "#4e7c5d",
            video: "#a0713f",
            text: "#5c7fa3",
            config: "#9a7fa6",
            audio: "#4e7c5d",
            director: "#5c7fa3",
            group: "#b3aeaa",
            danger: "#b0564b",
        },
    },
    dark: {
        name: "dark",
        canvas: {
            background: "#1a1816",
            dot: "rgba(246, 244, 242,.22)",
            line: "rgba(246, 244, 242,.10)",
            selectionStroke: "#f1f0ee",
            selectionFill: "rgba(241, 240, 238,.10)",
        },
        node: {
            label: "#ccc8c4",
            fill: "#2a2723",
            panel: "#22201d",
            panelHover: "#2a2723",
            stroke: "#423e3a",
            activeStroke: "#f1f0ee",
            placeholder: "#948f8a",
            text: "#f1f0ee",
            muted: "#ccc8c4",
            faint: "#948f8a",
        },
        toolbar: {
            panel: "rgba(34, 32, 29,.96)",
            border: "#423e3a",
            item: "#ccc8c4",
            itemHover: "#2a2723",
            activeBg: "#322e2a",
            activeText: "#f1f0ee",
        },
        type: {
            image: "#7fa88c",
            video: "#c08e4f",
            text: "#7e9dbf",
            config: "#9a8ab5",
            audio: "#7fa88c",
            director: "#7e9dbf",
            group: "#948f8a",
            danger: "#c97a6f",
        },
    },
    // 创作台浅白灰绿（与全局主题同源：#817b76 鼠尾草灰绿）
    warm: {
        name: "warm",
        canvas: {
            background: "#f6f4f2",
            dot: "rgba(129, 123, 118,.20)",
            line: "rgba(129, 123, 118,.12)",
            selectionStroke: "#332f2a",
            selectionFill: "rgba(51, 47, 42,.06)",
        },
        node: {
            label: "#726d67",
            fill: "#eceae7",
            panel: "#ffffff",
            panelHover: "#f9f7f5",
            stroke: "#e2dfdc",
            activeStroke: "#a0713f",
            placeholder: "#a49f9a",
            text: "#332f2a",
            muted: "#726d67",
            faint: "#a49f9a",
        },
        toolbar: {
            panel: "rgba(255,255,255,.96)",
            border: "#e2dfdc",
            item: "#726d67",
            itemHover: "#eceae7",
            activeBg: "#eceae7",
            activeText: "#332f2a",
        },
        type: {
            image: "#4e7c5d",
            video: "#a0713f",
            text: "#5c7fa3",
            config: "#9a7fa6",
            audio: "#4e7c5d",
            director: "#5c7fa3",
            group: "#a49f9a",
            danger: "#b0564b",
        },
    },
} as const;

export type CanvasTheme = (typeof canvasThemes)[CanvasColorTheme];
